services:
  cassandra:
  hostname: cassandra-1
  image: cassandra:latest
  command: /bin/bash -c "sleep 1 && echo ' -- Pausing to let system catch up ... -->' && /docker-entrypoint.sh cassandra -f"
  expose:
    - 7000
    - 7001
    - 7199
    - 9042
    - 9160
  karaf:
      image: karaf-distro-docker
      container_name: karaf
      ports:
        - "8181:8181"
      volumes:
        - /tmp/deploy/:/opt/karaf/deploy/
  restart: always